name: spatialmesh_ar
description: Revolutionary Infrastructure-Free Spatial Computing Network
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Material Design
  material_design_icons_flutter: ^7.0.7296
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  
  # AR & Spatial Computing
  ar_flutter_plugin_flutterflow: ^0.7.9
  camera: ^0.11.0+2
  sensors_plus: ^6.0.1
  vector_math: ^2.1.4
  
  # AWS Integration
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_api: ^2.0.0
  amplify_datastore: ^2.0.0
  amplify_storage_s3: ^2.0.0
  
  # Mesh Networking & Real-time
  webrtc_interface: ^1.1.0
  connectivity_plus: ^6.0.5
  network_info_plus: ^6.0.0
  socket_io_client: ^3.0.1
  nearby_connections: ^3.1.0
  
  # State Management
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # AI/ML Integration
  tflite_flutter: ^0.11.0
  google_ml_kit: ^0.18.0
  image: ^4.2.0
  
  # Blockchain & Payments
  web3dart: ^2.7.3
  bitcoin_flutter: ^2.1.0
  
  # Utilities & Helpers
  get_it: ^8.0.0
  injectable: ^2.4.4
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.4
  
  # Networking & HTTP
  dio: ^5.7.0
  http: ^1.2.2
  retry: ^3.1.2
  
  # JSON & Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  
  # Logging & Debugging
  logger: ^2.4.0
  flutter_dotenv: ^5.1.0
  
  # UI Enhancements
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  pull_to_refresh: ^2.0.0
  
  # GraphQL for AppSync
  graphql_flutter: ^5.1.2
  ferry: ^0.16.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
    
  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  injectable_generator: ^2.6.2
  freezed: ^2.5.7
  
  # Testing & Mocking
  mockito: ^5.4.4
  network_image_mock: ^2.1.1
  
  # Code Analysis
  very_good_analysis: ^6.0.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/models/
    - assets/sounds/
    - assets/textures/
    - ml_models/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700