AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB tables for SpatialMesh AR application

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']

Resources:
  SpatialAnchorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-SpatialAnchors
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: anchorId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: geohash
          AttributeType: S
      KeySchema:
        - AttributeName: anchorId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GeohashIndex
          KeySchema:
            - AttributeName: geohash
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  EarningsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-UserEarnings
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment

  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-EarningsTransactions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: transactionId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: transactionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserTransactionsIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  ReconciliationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-TransactionReconciliation
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: transactionId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: transactionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: TimestampIndex
          KeySchema:
            - AttributeName: timestamp
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  SpatialAnchorsTableName:
    Description: Name of the Spatial Anchors table
    Value: !Ref SpatialAnchorsTable
    Export:
      Name: !Sub ${Environment}-SpatialAnchorsTableName

  EarningsTableName:
    Description: Name of the User Earnings table
    Value: !Ref EarningsTable
    Export:
      Name: !Sub ${Environment}-EarningsTableName

  TransactionsTableName:
    Description: Name of the Earnings Transactions table
    Value: !Ref TransactionsTable
    Export:
      Name: !Sub ${Environment}-TransactionsTableName

  ReconciliationTableName:
    Description: Name of the Transaction Reconciliation table
    Value: !Ref ReconciliationTable
    Export:
      Name: !Sub ${Environment}-ReconciliationTableName